* Wed 29 Mar 2023 05:43:25 PM CEST
Starting with the Terraform book. Skipped to first exercise.
Setting up a simple web server on a VM in AWS.

* Chapter 2. Getting Started with Terraform
** Setting up your AWS account
*** Go to https://aws.amazon.com and set log in/create account.
*** Create an AWS access key and save it in password manager.
** Installing Terraform
*** Installing directly on desktop (instead of inside a VM). I have a feeling that Terraform installation wont pull too many dependencies, so I don't have to install it inside a VM like I would with some java or javascript developer environment.
**** Installing on Fedora
***** There is a repo package with version 1.4.4. Confirmed on Hashicorp's GitHub releases page that it is the latest version. Looks like a point for Fedora here.
***** There is also an emacs-terraform package. But maybe it would be better to install it from MELPA or ELPA (Emacs' own package repositories).
****** Chose to install it from Emacs' own repos.
**** Installing on Ubuntu
I already know that the latest package version is 1.4.4.

Ubuntu's version is 1.3.7

Checking if there are any big changes in 1.4 release that justify
adding Terraform PPA.

Don't see any.
** Setting environment variables with AWS access keys so Terraform can use AWS.
# We don't want keys in bash history. After entering the secret you
# need to press Ctrl-D to tell cat we've stopped writing.
export AWS_ACCESS_KEY_ID="$(cat -)"
export AWS_SECRET_ACCESS_KEY="$(cat -)"

** Deploying a single server

*** Choosing AWS region
Chosen Stockholm (eu-north-1) because it's close and cheap. Read [[https://www.concurrencylabs.com/blog/choose-your-aws-region-wisely/][this article]] to learn about it.
** Deploying a single web server
** Deploying a configurable web server
** Deploying a cluster of web servers
** Deploying a load balancer
** Cleaning up
